"""empty message

Revision ID: 33005ca96c7b
Revises: 9f56aeb8b6bf
Create Date: 2025-04-26 01:08:47.155463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33005ca96c7b'
down_revision = '9f56aeb8b6bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('migrations', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SCHEDULED'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_index('ix_migrations_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('migrations', schema=None) as batch_op:
        batch_op.create_index('ix_migrations_status', ['status'], unique=False)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.ENUM('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'SCHEDULED'),
               existing_nullable=False)

    # ### end Alembic commands ###
